# Copyright (C) 2015 Siavoosh Payandeh Azad
# this list contains all the 2D Deadlock-free turn models that provide full connectivity
# for connectivity metric, number of pairs of nodes that can communicate under the
# routing algorithm is used.

all_2d_turn_models = [['E2N', 'E2S', 'W2N', 'W2S'],
                      ['E2N', 'E2S', 'W2N', 'N2E'],
                      ['E2N', 'E2S', 'W2S', 'S2E'],
                      ['E2N', 'E2S', 'S2E', 'N2E'],
                      ['E2N', 'W2N', 'W2S', 'N2W'],
                      ['E2N', 'W2N', 'N2W', 'N2E'],
                      ['E2N', 'S2E', 'N2W', 'N2E'],
                      ['E2S', 'W2N', 'W2S', 'S2W'],
                      ['E2S', 'W2S', 'S2W', 'S2E'],
                      ['E2S', 'S2W', 'S2E', 'N2E'],
                      ['W2N', 'W2S', 'S2W', 'N2W'],
                      ['W2N', 'S2W', 'N2W', 'N2E'],
                      ['W2S', 'S2W', 'S2E', 'N2W'],
                      ['S2W', 'S2E', 'N2W', 'N2E'],
                      ['E2N', 'E2S', 'W2N', 'W2S', 'S2W'],
                      ['E2N', 'E2S', 'W2N', 'W2S', 'S2E'],
                      ['E2N', 'E2S', 'W2N', 'W2S', 'N2W'],
                      ['E2N', 'E2S', 'W2N', 'W2S', 'N2E'],
                      ['E2N', 'E2S', 'W2N', 'S2E', 'N2E'],
                      ['E2N', 'E2S', 'W2N', 'N2W', 'N2E'],
                      ['E2N', 'E2S', 'W2S', 'S2W', 'S2E'],
                      ['E2N', 'E2S', 'W2S', 'S2E', 'N2E'],
                      ['E2N', 'E2S', 'S2W', 'S2E', 'N2E'],
                      ['E2N', 'E2S', 'S2E', 'N2W', 'N2E'],
                      ['E2N', 'W2N', 'W2S', 'S2W', 'N2W'],
                      ['E2N', 'W2N', 'W2S', 'N2W', 'N2E'],
                      ['E2N', 'W2N', 'S2W', 'N2W', 'N2E'],
                      ['E2N', 'W2N', 'S2E', 'N2W', 'N2E'],
                      ['E2N', 'S2W', 'S2E', 'N2W', 'N2E'],
                      ['E2S', 'W2N', 'W2S', 'S2W', 'S2E'],
                      ['E2S', 'W2N', 'W2S', 'S2W', 'N2W'],
                      ['E2S', 'W2S', 'S2W', 'S2E', 'N2W'],
                      ['E2S', 'W2S', 'S2W', 'S2E', 'N2E'],
                      ['E2S', 'S2W', 'S2E', 'N2W', 'N2E'],
                      ['W2N', 'W2S', 'S2W', 'S2E', 'N2W'],
                      ['W2N', 'W2S', 'S2W', 'N2W', 'N2E'],
                      ['W2N', 'S2W', 'S2E', 'N2W', 'N2E'],
                      ['W2S', 'S2W', 'S2E', 'N2W', 'N2E'],
                      ['E2N', 'E2S', 'W2N', 'W2S', 'S2W', 'S2E'],
                      ['E2N', 'E2S', 'W2N', 'W2S', 'S2W', 'N2W'],
                      ['E2N', 'E2S', 'W2N', 'W2S', 'S2E', 'N2E'],		# West First
                      ['E2N', 'E2S', 'W2N', 'W2S', 'N2W', 'N2E'],		# North Last
                      ['E2N', 'E2S', 'W2N', 'S2E', 'N2W', 'N2E'],		# Negative First
                      ['E2N', 'E2S', 'W2S', 'S2W', 'S2E', 'N2E'],
                      ['E2N', 'E2S', 'S2W', 'S2E', 'N2W', 'N2E'],
                      ['E2N', 'W2N', 'W2S', 'S2W', 'N2W', 'N2E'],
                      ['E2N', 'W2N', 'S2W', 'S2E', 'N2W', 'N2E'],
                      ['E2S', 'W2N', 'W2S', 'S2W', 'S2E', 'N2W'],
                      ['E2S', 'W2S', 'S2W', 'S2E', 'N2W', 'N2E'],
                      ['W2N', 'W2S', 'S2W', 'S2E', 'N2W', 'N2E']]