#!/bin/bash

# if you run this script, the results would be generated in your result folder 
# at: ScheduleAndDepend/src/main/results 
# enjoy!


if [ ! -d "../results" ]; then
mkdir ../results/
else
rm -rf ../results/*
fi

cd ../python

FILES=Generated_Files/Turn_Model_Lists/*.txt
python Main.py -ETM 3D

DEST_FOLDER=../results/3D_TM
mkdir $DEST_FOLDER
for f in $FILES
do
   echo copying $f to $DEST_FOLDER 
   cp $f $DEST_FOLDER
done

# 3D deadlock free minimal and non-minimal 
python Main.py -ETMD 3D M 6

DEST_FOLDER=../results/3D_TM_DF_Minimal
mkdir $DEST_FOLDER
for f in $FILES
do
   echo copying $f to $DEST_FOLDER
   cp $f $DEST_FOLDER
   echo "-------------------------" >> $DEST_FOLDER/full_connectivity.txt
   echo $f >> $DEST_FOLDER/full_connectivity.txt
done

python Main.py -ETMD 3D NM 6

DEST_FOLDER=../results/3D_TM_DF_Non_Minimal
mkdir $DEST_FOLDER
for f in $FILES
do
   echo copying $f to $DEST_FOLDER
   cp $f $DEST_FOLDER
   echo "-------------------------" >> $DEST_FOLDER/full_connectivity.txt
   echo $f >> $DEST_FOLDER/full_connectivity.txt
done

# 3D turn models fault tolerant evaluation 
python Main.py -TMFT 3D M 6 -V
FILES=Generated_Files/Turn_Model_Eval/*.txt
DEST_FOLDER=../results/3D_TM_Minimal_Eval
mkdir $DEST_FOLDER
for f in $FILES
do
   echo copying $f to $DEST_FOLDER
   cp $f $DEST_FOLDER
done



